/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {SafeAreaView, StyleSheet} from 'react-native';
import MainView from './src/MainView';

export default class App extends Component<{}> {
  render() {
    return (
      <SafeAreaView style={styles.container}>
        <MainView />
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
